name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v5
    - name: set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Setup NDK r28
      run: sdkmanager "ndk;28.2.13676358"

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Debug
      run: ./gradlew assembleDebug
